import TotalColoring.MinSixCNFCore

/-!
# Formula-level threshold encoding for the minimum-six bridge

This file lifts the individual threshold-cell clauses from
`MinSixCNFCore` to the complete bounded table emitted by the research
generator.  It proves the one semantic direction needed by a future
certificate composition theorem: a primary assignment of exact cardinality
`k` has a canonical auxiliary extension satisfying the typed exact-count CNF.

The declarations do not serialize DIMACS integers, enumerate cage
descriptors, identify a generated byte stream, check an LRAT certificate, or
state that any graph-theoretic branch is unsatisfiable.
-/

namespace TotalColoring.MinSixCNFCore

/-- The two unit clauses asserting one threshold and refuting its successor. -/
def exactTerminalCNF {Var : Type*} (atLeast atLeastSucc : Var) : Formula Var :=
  [[.positive atLeast], [.negative atLeastSucc]]

@[simp] theorem satisfies_exactTerminalCNF_iff
    {Var : Type*} (σ : Assignment Var) (atLeast atLeastSucc : Var) :
    (exactTerminalCNF atLeast atLeastSucc).Satisfied σ ↔
      σ atLeast = true ∧ σ atLeastSucc = false := by
  cases ha : σ atLeast <;> cases hs : σ atLeastSucc <;>
    simp [Formula.Satisfied, Clause.Satisfied, exactTerminalCNF,
      Literal.eval, ha, hs]

@[simp] theorem Formula.satisfied_append_iff
    {Var : Type*} (σ : Assignment Var) (F K : Formula Var) :
    (F ++ K).Satisfied σ ↔ F.Satisfied σ ∧ K.Satisfied σ := by
  constructor
  · intro h
    constructor
    · intro C hC
      exact h C (List.mem_append.mpr (Or.inl hC))
    · intro C hC
      exact h C (List.mem_append.mpr (Or.inr hC))
  · rintro ⟨hF, hK⟩ C hC
    rcases List.mem_append.mp hC with hC | hC
    · exact hF C hC
    · exact hK C hC

namespace Threshold

/-- Clauses for one one-based threshold-table cell.

Rows and columns numbered zero are deliberately empty.  The valid cells use
exactly the generator's four cases: copy at `(1,1)`, first-column disjunction,
diagonal conjunction, and the four-clause interior recurrence. -/
def cellCNF {Primary : Type*} (x : Nat → Primary) :
    Nat → Nat → Formula (ThresholdVar Primary)
  | 0, _ => []
  | _, 0 => []
  | 1, 1 => copyCNF (.primary (x 0)) (.auxiliary 1 1)
  | 1, _ + 2 => []
  | i + 2, 1 =>
      orCNF (.auxiliary (i + 1) 1) (.primary (x (i + 1)))
        (.auxiliary (i + 2) 1)
  | i + 2, j + 2 =>
      if j = i then
        andCNF (.primary (x (i + 1))) (.auxiliary (i + 1) (i + 1))
          (.auxiliary (i + 2) (i + 2))
      else
        recurrenceCNF (.auxiliary (i + 1) (j + 2))
          (.primary (x (i + 1))) (.auxiliary (i + 1) (j + 1))
          (.auxiliary (i + 2) (j + 2))

/-- The first `min i top` cells in one one-based row. -/
def rowCNF {Primary : Type*}
    (x : Nat → Primary) (top i : Nat) : Formula (ThresholdVar Primary) :=
  (List.range (min i top)).flatMap fun j => cellCNF x i (j + 1)

/-- The bounded threshold table on the first `n` primary inputs. -/
def tableCNF {Primary : Type*}
    (x : Nat → Primary) (n top : Nat) : Formula (ThresholdVar Primary) :=
  (List.range n).flatMap fun i => rowCNF x top (i + 1)

/-- The typed counterpart of the generator's exact-count threshold block. -/
def exactCountCNF {Primary : Type*}
    (x : Nat → Primary) (n k : Nat) : Formula (ThresholdVar Primary) :=
  tableCNF x n (k + 1) ++
    exactTerminalCNF (.auxiliary n k) (.auxiliary n (k + 1))

/-- Every threshold cell is satisfied by the canonical table extension. -/
theorem extension_satisfies_cell
    {Primary : Type*} (σ : Assignment Primary) (x : Nat → Primary)
    (i j : Nat) :
    (cellCNF x i j).Satisfied (extension σ x) := by
  cases i with
  | zero =>
      simp [cellCNF, Formula.Satisfied]
  | succ i =>
      cases j with
      | zero =>
          simp [cellCNF, Formula.Satisfied]
      | succ j =>
          cases i with
          | zero =>
              cases j with
              | zero =>
                  simp [cellCNF]
              | succ j =>
                  simp [cellCNF, Formula.Satisfied]
          | succ i =>
              cases j with
              | zero =>
                  simp [cellCNF]
              | succ j =>
                  by_cases hji : j = i
                  · subst j
                    simpa [cellCNF] using
                      extension_satisfies_diagonal σ x (i + 1)
                  · simp [cellCNF, hji]

/-- The canonical extension satisfies every clause in one bounded row. -/
theorem extension_satisfies_row
    {Primary : Type*} (σ : Assignment Primary) (x : Nat → Primary)
    (top i : Nat) :
    (rowCNF x top i).Satisfied (extension σ x) := by
  intro C hC
  rcases List.mem_flatMap.mp hC with ⟨j, _, hC⟩
  exact (extension_satisfies_cell σ x i (j + 1)) C hC

/-- The canonical extension satisfies the complete bounded threshold table. -/
theorem extension_satisfies_table
    {Primary : Type*} (σ : Assignment Primary) (x : Nat → Primary)
    (n top : Nat) :
    (tableCNF x n top).Satisfied (extension σ x) := by
  intro C hC
  rcases List.mem_flatMap.mp hC with ⟨i, _, hC⟩
  exact (extension_satisfies_row σ x top (i + 1)) C hC

/-- Exact primary cardinality supplies a satisfying canonical extension of
the typed exact-count CNF. -/
theorem extension_satisfies_exactCountCNF
    {Primary : Type*} (σ : Assignment Primary) (x : Nat → Primary)
    (n k : Nat) (hcount : trueCount σ x n = k) :
    (exactCountCNF x n k).Satisfied (extension σ x) := by
  rw [exactCountCNF, Formula.satisfied_append_iff,
    satisfies_exactTerminalCNF_iff]
  refine ⟨extension_satisfies_table σ x n (k + 1), ?_⟩
  simpa using exact_threshold_values σ x n k hcount

/-- On the canonical extension, satisfying the typed exact-count CNF is
equivalent to the primary assignment having the requested cardinality. -/
theorem extension_satisfies_exactCountCNF_iff
    {Primary : Type*} (σ : Assignment Primary) (x : Nat → Primary)
    (n k : Nat) :
    (exactCountCNF x n k).Satisfied (extension σ x) ↔
      trueCount σ x n = k := by
  constructor
  · rw [exactCountCNF, Formula.satisfied_append_iff,
      satisfies_exactTerminalCNF_iff]
    rintro ⟨_, hk, hksucc⟩
    change value σ x n k = true at hk
    change value σ x n (k + 1) = false at hksucc
    have hle := (value_eq_true_iff_le_trueCount σ x n k).1 hk
    have hnle : ¬k + 1 ≤ trueCount σ x n := by
      intro hleSucc
      have hv :=
        (value_eq_true_iff_le_trueCount σ x n (k + 1)).2 hleSucc
      rw [hksucc] at hv
      contradiction
    omega
  · exact extension_satisfies_exactCountCNF σ x n k

end Threshold

end TotalColoring.MinSixCNFCore
