import TotalColoring.Auxiliary
import TotalColoring.Distinguished

/-!
# The fixed pair/singleton auxiliary extension

This module constructs the first concrete seam in the auxiliary reduction from
a supplied pair/singleton witness.  The new auxiliary vertex is `none`; every
original vertex is copied as `some v`.  A singleton selects the edge
`s(none, some v)`, while a paired vertex selects the edge joining its two
copied class members.

The auxiliary graph is the union of the copied original graph and the graph
generated by the selector finset.  The module proves the corresponding
`Auxiliary.Extension`, exact selector coverage, and the qualitative
matching-plus-full-star decomposition.  It deliberately leaves the numerical
degree and cardinality identities, construction of a witness from an
equitable partition, and unconditional membership in `InAuxiliaryClass` open.
-/

namespace TotalColoring.Auxiliary

universe u

variable {V : Type u} {G : SimpleGraph V}

/-- A fixed partition of the vertices into singleton and pair classes.

`partner v = none` records a singleton class.  If `partner v = some w`, the
remaining fields say that `v` and `w` are distinct mutual partners and are
nonadjacent in `G`.  Thus every supplied pair class is independent. -/
structure PairSingletonWitness (G : SimpleGraph V) where
  partner : V → Option V
  partner_ne : ∀ {v w}, partner v = some w → v ≠ w
  partner_symm : ∀ {v w}, partner v = some w → partner w = some v
  partner_nonadjacent : ∀ {v w}, partner v = some w → ¬G.Adj v w

namespace PairSingletonWitness

variable (P : PairSingletonWitness G)

/-- The auxiliary edge whose color will decode to the color of `v`. -/
def selector (v : V) : Sym2 (Option V) :=
  match P.partner v with
  | none => s(none, some v)
  | some w => s(some v, some w)

/-- Every original vertex is an endpoint of its selector edge. -/
theorem some_mem_selector (v : V) : some v ∈ P.selector v := by
  cases hpartner : P.partner v with
  | none => simp [selector, hpartner]
  | some w => simp [selector, hpartner]

@[simp]
theorem none_mem_selector_iff (v : V) :
    (none : Option V) ∈ P.selector v ↔ P.partner v = none := by
  cases hpartner : P.partner v with
  | none => simp [selector, hpartner]
  | some w => simp [selector, hpartner]

@[simp]
theorem some_mem_selector_iff {u v : V} :
    some u ∈ P.selector v ↔ u = v ∨ P.partner v = some u := by
  cases hpartner : P.partner v with
  | none => simp [selector, hpartner]
  | some w =>
      simp only [selector, hpartner, Sym2.mem_iff, Option.some.injEq]
      constructor
      · rintro (huv | huw)
        · exact Or.inl huv
        · exact Or.inr huw.symm
      · rintro (huv | hwu)
        · exact Or.inl huv
        · exact Or.inr hwu.symm

/-- Selector pairs are genuine edges rather than diagonal unordered pairs. -/
theorem selector_not_isDiag (v : V) : ¬(P.selector v).IsDiag := by
  cases hpartner : P.partner v with
  | none => simp [selector, hpartner]
  | some w =>
      simpa [selector, hpartner] using P.partner_ne hpartner

/-- Partners select the same auxiliary edge. -/
theorem selector_eq_of_partner {v w : V} (hpartner : P.partner v = some w) :
    P.selector w = P.selector v := by
  have hreverse := P.partner_symm hpartner
  simpa only [selector, hpartner, hreverse] using
    (Sym2.eq_swap : s(some w, some v) = s(some v, some w))

/-- Adjacent original vertices select distinct auxiliary edges. -/
theorem selector_ne_of_adj {v w : V} (hadj : G.Adj v w) :
    P.selector v ≠ P.selector w := by
  cases hv : P.partner v with
  | none =>
      cases hw : P.partner w with
      | none =>
          intro heq
          have hvw : v = w := by
            simpa [selector, hv, hw, Sym2.eq_iff] using heq
          exact hadj.ne hvw
      | some z => simp [selector, hv, hw]
  | some y =>
      cases hw : P.partner w with
      | none => simp [selector, hv, hw]
      | some z =>
          intro heq
          have hcases : (v = w ∧ y = z) ∨ (v = z ∧ y = w) := by
            simpa only [selector, hv, hw, Sym2.eq_iff, Option.some.injEq] using heq
          rcases hcases with ⟨hvw, _⟩ | ⟨hvz, hyw⟩
          · exact hadj.ne hvw
          · subst z
            subst y
            exact P.partner_nonadjacent hv hadj

section Finite

variable [Fintype V] [DecidableEq V]

/-- The underlying-pair representation of all selector edges. -/
def distinguished : Finset (Sym2 (Option V)) :=
  Finset.univ.image P.selector

/-- Every selector belongs to the finite distinguished family. -/
theorem selector_mem_distinguished (v : V) :
    P.selector v ∈ P.distinguished := by
  exact Finset.mem_image.mpr ⟨v, Finset.mem_univ v, rfl⟩

/-- A distinguished edge containing a copied original vertex is necessarily
the selector chosen by that vertex. -/
theorem eq_selector_of_mem_distinguished_of_some_mem
    {e : Sym2 (Option V)} (he : e ∈ P.distinguished) {v : V}
    (hv : some v ∈ e) : e = P.selector v := by
  rcases Finset.mem_image.mp he with ⟨u, _, rfl⟩
  rw [some_mem_selector_iff] at hv
  rcases hv with huv | hpartner
  · subst u
    rfl
  · exact (P.selector_eq_of_partner hpartner).symm

/-- Every copied original vertex lies on exactly one distinguished edge. -/
theorem distinguished_exact_coverage (v : V) :
    ∃! e : Sym2 (Option V), e ∈ P.distinguished ∧ some v ∈ e := by
  refine ⟨P.selector v, ⟨P.selector_mem_distinguished v,
    P.some_mem_selector v⟩, ?_⟩
  intro e he
  exact P.eq_selector_of_mem_distinguished_of_some_mem he.1 he.2

/-- The off-center part of the distinguished family. -/
def matchingPart : Finset (Sym2 (Option V)) :=
  P.distinguished.filter fun e ↦ (none : Option V) ∉ e

@[simp]
theorem mem_matchingPart {e : Sym2 (Option V)} :
    e ∈ P.matchingPart ↔ e ∈ P.distinguished ∧ (none : Option V) ∉ e := by
  simp [matchingPart]

/-- No edge in the matching part contains the new center. -/
theorem matchingPart_off_center {e : Sym2 (Option V)}
    (he : e ∈ P.matchingPart) : (none : Option V) ∉ e :=
  (P.mem_matchingPart.mp he).2

/-- The off-center distinguished edges form a matching. -/
theorem matchingPart_isEdgeMatching : IsEdgeMatching P.matchingPart := by
  intro e he f hf hef v hve hvf
  cases v with
  | none => exact P.matchingPart_off_center he hve
  | some v =>
      apply hef
      calc
        e = P.selector v :=
          P.eq_selector_of_mem_distinguished_of_some_mem
            (P.mem_matchingPart.mp he).1 hve
        _ = f :=
          (P.eq_selector_of_mem_distinguished_of_some_mem
            (P.mem_matchingPart.mp hf).1 hvf).symm

/-- The ordinary auxiliary graph: the copied original graph together with all
selector edges. -/
def auxiliaryGraph : SimpleGraph (Option V) :=
  G.map Function.Embedding.some ⊔
    SimpleGraph.fromEdgeSet (P.distinguished : Set (Sym2 (Option V)))

/-- Every selector is an edge of the concrete auxiliary graph. -/
theorem selector_mem_auxiliaryGraph (v : V) :
    P.selector v ∈ P.auxiliaryGraph.edgeSet := by
  rw [auxiliaryGraph, SimpleGraph.edgeSet_sup]
  right
  rw [SimpleGraph.edgeSet_fromEdgeSet]
  exact ⟨P.selector_mem_distinguished v, P.selector_not_isDiag v⟩

/-- Every distinguished pair is an edge of the concrete auxiliary graph. -/
theorem distinguished_mem_auxiliaryGraph_edgeSet
    {e : Sym2 (Option V)} (he : e ∈ P.distinguished) :
    e ∈ P.auxiliaryGraph.edgeSet := by
  rcases Finset.mem_image.mp he with ⟨v, _, rfl⟩
  exact P.selector_mem_auxiliaryGraph v

/-- An auxiliary edge incident with the new center belongs to the
distinguished family. -/
theorem mem_distinguished_of_mem_auxiliaryGraph_of_none_mem
    {e : Sym2 (Option V)} (he : e ∈ P.auxiliaryGraph.edgeSet)
    (hnone : (none : Option V) ∈ e) : e ∈ P.distinguished := by
  rw [auxiliaryGraph, SimpleGraph.edgeSet_sup] at he
  rcases he with hcopied | hselected
  · rw [SimpleGraph.edgeSet_map] at hcopied
    rcases hcopied with ⟨f, _, rfl⟩
    rw [Function.Embedding.sym2Map_apply] at hnone
    rcases Sym2.mem_map.mp hnone with ⟨v, _, hv⟩
    cases hv
  · rw [SimpleGraph.edgeSet_fromEdgeSet] at hselected
    exact hselected.1

/-- The new center is adjacent precisely to copied singleton vertices. -/
theorem auxiliaryGraph_adj_none_some_iff (v : V) :
    P.auxiliaryGraph.Adj none (some v) ↔ P.partner v = none := by
  constructor
  · intro hadj
    have hedge : s(none, some v) ∈ P.auxiliaryGraph.edgeSet := by
      rw [SimpleGraph.mem_edgeSet]
      exact hadj
    have hdistinguished :=
      P.mem_distinguished_of_mem_auxiliaryGraph_of_none_mem hedge
        (Sym2.mem_mk_left _ _)
    have heq : s(none, some v) = P.selector v :=
      P.eq_selector_of_mem_distinguished_of_some_mem hdistinguished
        (Sym2.mem_mk_right _ _)
    apply (P.none_mem_selector_iff v).mp
    rw [← heq]
    exact Sym2.mem_mk_left _ _
  · intro hpartner
    rw [← SimpleGraph.mem_edgeSet]
    simpa [selector, hpartner] using P.selector_mem_auxiliaryGraph v

/-- Endpoints of off-center distinguished edges are not neighbors of the new
center. -/
theorem matchingPart_avoids_center_neighbors
    {e : Sym2 (Option V)} (he : e ∈ P.matchingPart) {v : Option V}
    (hv : v ∈ e) : ¬P.auxiliaryGraph.Adj none v := by
  cases v with
  | none => exact P.auxiliaryGraph.loopless.irrefl none
  | some v =>
      intro hadj
      have hpartner : P.partner v = none :=
        (P.auxiliaryGraph_adj_none_some_iff v).mp hadj
      have heq : e = P.selector v :=
        P.eq_selector_of_mem_distinguished_of_some_mem
          (P.mem_matchingPart.mp he).1 hv
      apply P.matchingPart_off_center he
      rw [heq]
      exact (P.none_mem_selector_iff v).2 hpartner

/-- The center incidence finset is exactly the center-incident portion of the
distinguished family. -/
theorem mem_incidenceFinset_none_iff
    [DecidableRel P.auxiliaryGraph.Adj] {e : Sym2 (Option V)} :
    e ∈ P.auxiliaryGraph.incidenceFinset none ↔
      e ∈ P.distinguished ∧ (none : Option V) ∈ e := by
  rw [SimpleGraph.mem_incidenceFinset]
  change
    (e ∈ P.auxiliaryGraph.edgeSet ∧ (none : Option V) ∈ e) ↔
      e ∈ P.distinguished ∧ (none : Option V) ∈ e
  constructor
  · rintro ⟨he, hnone⟩
    exact ⟨P.mem_distinguished_of_mem_auxiliaryGraph_of_none_mem he hnone,
      hnone⟩
  · rintro ⟨he, hnone⟩
    exact ⟨P.distinguished_mem_auxiliaryGraph_edgeSet he, hnone⟩

/-- The distinguished family decomposes as the off-center matching together
with the full star at the new center. -/
theorem distinguished_decomposition
    [DecidableRel P.auxiliaryGraph.Adj] :
    P.distinguished =
      P.matchingPart ∪ P.auxiliaryGraph.incidenceFinset none := by
  ext e
  rw [Finset.mem_union, P.mem_matchingPart,
    P.mem_incidenceFinset_none_iff]
  constructor
  · intro he
    by_cases hnone : (none : Option V) ∈ e
    · exact Or.inr ⟨he, hnone⟩
    · exact Or.inl ⟨he, hnone⟩
  · rintro (⟨he, _⟩ | ⟨he, _⟩) <;> exact he

/-- Once the three numerical obligations are supplied, the concrete
pair/singleton construction is a member of the structural auxiliary class. -/
theorem isAuxiliaryClassMember_of_numeric (D : ℕ)
    [DecidableRel P.auxiliaryGraph.Adj]
    (hcard : P.distinguished.card = D)
    (hmax : P.auxiliaryGraph.maxDegree ≤ D)
    (hcenter : 2 ≤ P.auxiliaryGraph.degree none ∧
      P.auxiliaryGraph.degree none ≤ D) :
    IsAuxiliaryClassMember D P.auxiliaryGraph none P.distinguished
      P.matchingPart := by
  refine
    { distinguished_edges := ?_
      matching := P.matchingPart_isEdgeMatching
      matching_off_center := ?_
      matching_avoids_center_neighbors := ?_
      decomposition := P.distinguished_decomposition
      exact_coverage := ?_
      card_distinguished := hcard
      maxDegree_bound := hmax
      center_degree := hcenter }
  · intro e he
    exact P.distinguished_mem_auxiliaryGraph_edgeSet he
  · intro e he
    exact P.matchingPart_off_center he
  · intro e he v hv
    exact P.matchingPart_avoids_center_neighbors he hv
  · intro v hv
    cases v with
    | none => exact (hv rfl).elim
    | some v => exact P.distinguished_exact_coverage v

/-- The selected auxiliary edge as an element of the auxiliary edge subtype. -/
def classEdge (v : V) : P.auxiliaryGraph.edgeSet :=
  ⟨P.selector v, P.selector_mem_auxiliaryGraph v⟩

/-- The canonical copy of `G` inside the concrete auxiliary graph. -/
def originalCopy : SimpleGraph.Copy G P.auxiliaryGraph :=
  (SimpleGraph.Copy.ofLE _ _ le_sup_left).comp
    (SimpleGraph.Embedding.map Function.Embedding.some G).toCopy

@[simp]
theorem originalCopy_apply (v : V) : P.originalCopy v = some v := by
  rfl

/-- The copied auxiliary edge corresponding to an original edge. -/
def originalEdge (e : G.edgeSet) : P.auxiliaryGraph.edgeSet :=
  P.originalCopy.toLineGraphEmbedding e

@[simp]
theorem originalEdge_val (e : G.edgeSet) :
    (P.originalEdge e : Sym2 (Option V)) =
      (e : Sym2 V).map Option.some := by
  change Sym2.map P.originalCopy (e : Sym2 V) =
    Sym2.map Option.some (e : Sym2 V)
  apply Sym2.map_congr
  intro v _
  exact P.originalCopy_apply v

omit [Fintype V] [DecidableEq V] in
/-- A selector edge cannot coincide with a copied original edge incident with
the vertex which chose it. -/
theorem selector_ne_mapped_original_of_incident
    {v : V} {e : G.edgeSet} (hve : Incident v e) :
    P.selector v ≠ (e : Sym2 V).map Option.some := by
  intro heq
  cases hpartner : P.partner v with
  | none =>
      have hnone : (none : Option V) ∈ (e : Sym2 V).map Option.some := by
        rw [← heq]
        simp [selector, hpartner]
      simp at hnone
  | some w =>
      have hsome : some w ∈ (e : Sym2 V).map Option.some := by
        rw [← heq]
        simp [selector, hpartner]
      rcases Sym2.mem_map.mp hsome with ⟨w', hw'e, hsomeEq⟩
      have hw' : w' = w := Option.some.inj hsomeEq
      subst w'
      have hedge : (e : Sym2 V) = s(v, w) :=
        (Sym2.mem_and_mem_iff (P.partner_ne hpartner)).mp ⟨hve, hw'e⟩
      apply P.partner_nonadjacent hpartner
      rw [← SimpleGraph.mem_edgeSet, ← hedge]
      exact e.2

/-- The concrete pair/singleton construction preserves the three conflict
relations required by the abstract decoding interface. -/
def extension : Extension G P.auxiliaryGraph where
  classEdge := P.classEdge
  originalEdge := P.originalEdge
  classEdge_ne_of_adj := fun hadj ↦ by
    intro heq
    apply P.selector_ne_of_adj hadj
    exact congrArg Subtype.val heq
  originalEdge_adj := fun hadj ↦ by
    exact P.originalCopy.toLineGraphEmbedding.toHom.map_adj hadj
  classEdge_adj_original := fun {v e} hve ↦ by
    rw [SimpleGraph.lineGraph_adj_iff_exists]
    refine ⟨?_, some v, ?_, ?_⟩
    · intro heq
      apply P.selector_ne_mapped_original_of_incident hve
      have hval := congrArg Subtype.val heq
      simpa only [classEdge, originalEdge_val] using hval
    · exact P.some_mem_selector v
    · rw [originalEdge_val]
      exact Sym2.mem_map.mpr ⟨v, hve, rfl⟩

/-- Every selector used by the concrete extension lies in the distinguished
edge set expected by the abstract transfer theorem. -/
theorem classEdge_mem_distinguishedEdgeSet (v : V) :
    P.extension.classEdge v ∈
      distinguishedEdgeSet P.auxiliaryGraph P.distinguished := by
  change P.selector v ∈ P.distinguished
  exact P.selector_mem_distinguished v

end Finite

end PairSingletonWitness

end TotalColoring.Auxiliary
