import TotalColoring.Auxiliary
import TotalColoring.Distinguished
import Mathlib.Combinatorics.SimpleGraph.DegreeSum
import Mathlib.Data.Fintype.BigOperators

/-!
# The fixed pair/singleton auxiliary extension

This module constructs the first concrete seam in the auxiliary reduction from
a supplied pair/singleton witness.  The new auxiliary vertex is `none`; every
original vertex is copied as `some v`.  A singleton selects the edge
`s(none, some v)`, while a paired vertex selects the edge joining its two
copied class members.

The auxiliary graph is the union of the copied original graph and the graph
generated by the selector finset.  The module proves the corresponding
`Auxiliary.Extension`, exact selector coverage, the matching-plus-full-star
decomposition, and the intrinsic degree and orbit-count identities.  Its final
wrappers still require the exact class count and order/degree bounds.  The
construction of a witness from an equitable partition remains outside this
module.
-/

namespace TotalColoring.Auxiliary

universe u

variable {V : Type u} {G : SimpleGraph V}

/-- A fixed partition of the vertices into singleton and pair classes.

`partner v = none` records a singleton class.  If `partner v = some w`, the
remaining fields say that `v` and `w` are distinct mutual partners and are
nonadjacent in `G`.  Thus every supplied pair class is independent. -/
structure PairSingletonWitness (G : SimpleGraph V) where
  partner : V → Option V
  partner_ne : ∀ {v w}, partner v = some w → v ≠ w
  partner_symm : ∀ {v w}, partner v = some w → partner w = some v
  partner_nonadjacent : ∀ {v w}, partner v = some w → ¬G.Adj v w

namespace PairSingletonWitness

variable (P : PairSingletonWitness G)

/-- The auxiliary edge whose color will decode to the color of `v`. -/
def selector (v : V) : Sym2 (Option V) :=
  match P.partner v with
  | none => s(none, some v)
  | some w => s(some v, some w)

/-- Every original vertex is an endpoint of its selector edge. -/
theorem some_mem_selector (v : V) : some v ∈ P.selector v := by
  cases hpartner : P.partner v with
  | none => simp [selector, hpartner]
  | some w => simp [selector, hpartner]

@[simp]
theorem none_mem_selector_iff (v : V) :
    (none : Option V) ∈ P.selector v ↔ P.partner v = none := by
  cases hpartner : P.partner v with
  | none => simp [selector, hpartner]
  | some w => simp [selector, hpartner]

@[simp]
theorem some_mem_selector_iff {u v : V} :
    some u ∈ P.selector v ↔ u = v ∨ P.partner v = some u := by
  cases hpartner : P.partner v with
  | none => simp [selector, hpartner]
  | some w =>
      simp only [selector, hpartner, Sym2.mem_iff, Option.some.injEq]
      constructor
      · rintro (huv | huw)
        · exact Or.inl huv
        · exact Or.inr huw.symm
      · rintro (huv | hwu)
        · exact Or.inl huv
        · exact Or.inr hwu.symm

/-- Selector pairs are genuine edges rather than diagonal unordered pairs. -/
theorem selector_not_isDiag (v : V) : ¬(P.selector v).IsDiag := by
  cases hpartner : P.partner v with
  | none => simp [selector, hpartner]
  | some w =>
      simpa [selector, hpartner] using P.partner_ne hpartner

/-- Partners select the same auxiliary edge. -/
theorem selector_eq_of_partner {v w : V} (hpartner : P.partner v = some w) :
    P.selector w = P.selector v := by
  have hreverse := P.partner_symm hpartner
  simpa only [selector, hpartner, hreverse] using
    (Sym2.eq_swap : s(some w, some v) = s(some v, some w))

/-- Two vertices select the same edge exactly when they are equal or form one
of the supplied pair classes. -/
theorem selector_eq_selector_iff (u v : V) :
    P.selector u = P.selector v ↔ u = v ∨ P.partner v = some u := by
  constructor
  · intro heq
    apply P.some_mem_selector_iff.mp
    rw [← heq]
    exact P.some_mem_selector u
  · rintro (rfl | hpartner)
    · rfl
    · exact P.selector_eq_of_partner hpartner

/-- Adjacent original vertices select distinct auxiliary edges. -/
theorem selector_ne_of_adj {v w : V} (hadj : G.Adj v w) :
    P.selector v ≠ P.selector w := by
  cases hv : P.partner v with
  | none =>
      cases hw : P.partner w with
      | none =>
          intro heq
          have hvw : v = w := by
            simpa [selector, hv, hw, Sym2.eq_iff] using heq
          exact hadj.ne hvw
      | some z => simp [selector, hv, hw]
  | some y =>
      cases hw : P.partner w with
      | none => simp [selector, hv, hw]
      | some z =>
          intro heq
          have hcases : (v = w ∧ y = z) ∨ (v = z ∧ y = w) := by
            simpa only [selector, hv, hw, Sym2.eq_iff, Option.some.injEq] using heq
          rcases hcases with ⟨hvw, _⟩ | ⟨hvz, hyw⟩
          · exact hadj.ne hvw
          · subst z
            subst y
            exact P.partner_nonadjacent hv hadj

section Finite

variable [Fintype V] [DecidableEq V]

/-- The original vertices which form singleton classes. -/
def singletonVertices : Finset V :=
  Finset.univ.filter fun v ↦ P.partner v = none

omit [DecidableEq V] in
@[simp]
theorem mem_singletonVertices {v : V} :
    v ∈ P.singletonVertices ↔ P.partner v = none := by
  simp [singletonVertices]

/-- The underlying-pair representation of all selector edges. -/
def distinguished : Finset (Sym2 (Option V)) :=
  Finset.univ.image P.selector

/-- Every selector belongs to the finite distinguished family. -/
theorem selector_mem_distinguished (v : V) :
    P.selector v ∈ P.distinguished := by
  exact Finset.mem_image.mpr ⟨v, Finset.mem_univ v, rfl⟩

/-- A distinguished edge containing a copied original vertex is necessarily
the selector chosen by that vertex. -/
theorem eq_selector_of_mem_distinguished_of_some_mem
    {e : Sym2 (Option V)} (he : e ∈ P.distinguished) {v : V}
    (hv : some v ∈ e) : e = P.selector v := by
  rcases Finset.mem_image.mp he with ⟨u, _, rfl⟩
  rw [some_mem_selector_iff] at hv
  rcases hv with huv | hpartner
  · subst u
    rfl
  · exact (P.selector_eq_of_partner hpartner).symm

/-- Every copied original vertex lies on exactly one distinguished edge. -/
theorem distinguished_exact_coverage (v : V) :
    ∃! e : Sym2 (Option V), e ∈ P.distinguished ∧ some v ∈ e := by
  refine ⟨P.selector v, ⟨P.selector_mem_distinguished v,
    P.some_mem_selector v⟩, ?_⟩
  intro e he
  exact P.eq_selector_of_mem_distinguished_of_some_mem he.1 he.2

/-- The selector-only graph used to count the singleton/pair orbits. -/
def selectorGraph : SimpleGraph (Option V) :=
  SimpleGraph.fromEdgeSet (P.distinguished : Set (Sym2 (Option V)))

/-- The selector-only graph has exactly the distinguished edges. -/
theorem selectorGraph_edgeFinset
    [DecidableRel P.selectorGraph.Adj] :
    P.selectorGraph.edgeFinset = P.distinguished := by
  ext e
  rw [SimpleGraph.mem_edgeFinset, selectorGraph,
    SimpleGraph.edgeSet_fromEdgeSet]
  simp only [Set.mem_sdiff, Finset.mem_coe, Sym2.mem_diagSet]
  constructor
  · exact fun he ↦ he.1
  · intro he
    refine ⟨he, ?_⟩
    rcases Finset.mem_image.mp he with ⟨v, _, rfl⟩
    exact P.selector_not_isDiag v

/-- In the selector-only graph, the center is adjacent precisely to copied
singleton vertices. -/
theorem selectorGraph_adj_none_some_iff (v : V) :
    P.selectorGraph.Adj none (some v) ↔ P.partner v = none := by
  rw [selectorGraph, SimpleGraph.fromEdgeSet_adj]
  constructor
  · intro hadj
    have heq : s(none, some v) = P.selector v :=
      P.eq_selector_of_mem_distinguished_of_some_mem hadj.1
        (Sym2.mem_mk_right _ _)
    apply (P.none_mem_selector_iff v).mp
    rw [← heq]
    exact Sym2.mem_mk_left _ _
  · intro hpartner
    refine ⟨?_, by simp⟩
    simpa [selector, hpartner] using P.selector_mem_distinguished v

/-- Each copied original vertex has degree one in the selector-only graph. -/
theorem selectorGraph_degree_some_eq_one
    [DecidableRel P.selectorGraph.Adj] (v : V) :
    P.selectorGraph.degree (some v) = 1 := by
  have hincidence :
      P.selectorGraph.incidenceFinset (some v) = {P.selector v} := by
    ext e
    rw [SimpleGraph.mem_incidenceFinset]
    simp only [SimpleGraph.incidenceSet, Set.mem_setOf_eq,
      Finset.mem_singleton]
    constructor
    · rintro ⟨he, hv⟩
      apply P.eq_selector_of_mem_distinguished_of_some_mem _ hv
      rw [selectorGraph, SimpleGraph.edgeSet_fromEdgeSet] at he
      exact he.1
    · rintro rfl
      refine ⟨?_, P.some_mem_selector v⟩
      rw [selectorGraph, SimpleGraph.edgeSet_fromEdgeSet]
      exact ⟨P.selector_mem_distinguished v, by
        simpa only [Sym2.mem_diagSet] using P.selector_not_isDiag v⟩
  rw [← P.selectorGraph.card_incidenceFinset_eq_degree,
    hincidence, Finset.card_singleton]

/-- The center degree in the selector-only graph is the singleton count. -/
theorem selectorGraph_degree_none_eq_singletonVertices_card
    [DecidableRel P.selectorGraph.Adj] :
    P.selectorGraph.degree none = P.singletonVertices.card := by
  have hneighbors :
      P.selectorGraph.neighborFinset none =
        P.singletonVertices.map Function.Embedding.some := by
    ext v
    cases v with
    | none => simp [SimpleGraph.mem_neighborFinset]
    | some v =>
        rw [SimpleGraph.mem_neighborFinset,
          P.selectorGraph_adj_none_some_iff]
        simp
  change (P.selectorGraph.neighborFinset none).card =
    P.singletonVertices.card
  rw [hneighbors, Finset.card_map]

/-- The intrinsic orbit count for a fixed partition into singleton and pair
classes.  It is stated additively and does not require a parity hypothesis. -/
theorem card_add_singletonVertices_card_eq_two_mul_distinguished_card :
    Fintype.card V + P.singletonVertices.card =
      2 * P.distinguished.card := by
  classical
  calc
    Fintype.card V + P.singletonVertices.card =
        P.singletonVertices.card + Fintype.card V := Nat.add_comm _ _
    _ = 2 * P.distinguished.card := by
      simpa [Fintype.sum_option,
          P.selectorGraph_degree_none_eq_singletonVertices_card,
          P.selectorGraph_degree_some_eq_one, Finset.sum_const,
          P.selectorGraph_edgeFinset] using
        P.selectorGraph.sum_degrees_eq_twice_card_edges

/-- The off-center part of the distinguished family. -/
def matchingPart : Finset (Sym2 (Option V)) :=
  P.distinguished.filter fun e ↦ (none : Option V) ∉ e

@[simp]
theorem mem_matchingPart {e : Sym2 (Option V)} :
    e ∈ P.matchingPart ↔ e ∈ P.distinguished ∧ (none : Option V) ∉ e := by
  simp [matchingPart]

/-- No edge in the matching part contains the new center. -/
theorem matchingPart_off_center {e : Sym2 (Option V)}
    (he : e ∈ P.matchingPart) : (none : Option V) ∉ e :=
  (P.mem_matchingPart.mp he).2

/-- The off-center distinguished edges form a matching. -/
theorem matchingPart_isEdgeMatching : IsEdgeMatching P.matchingPart := by
  intro e he f hf hef v hve hvf
  cases v with
  | none => exact P.matchingPart_off_center he hve
  | some v =>
      apply hef
      calc
        e = P.selector v :=
          P.eq_selector_of_mem_distinguished_of_some_mem
            (P.mem_matchingPart.mp he).1 hve
        _ = f :=
          (P.eq_selector_of_mem_distinguished_of_some_mem
            (P.mem_matchingPart.mp hf).1 hvf).symm

/-- The ordinary auxiliary graph: the copied original graph together with all
selector edges. -/
def auxiliaryGraph : SimpleGraph (Option V) :=
  G.map Function.Embedding.some ⊔
    SimpleGraph.fromEdgeSet (P.distinguished : Set (Sym2 (Option V)))

/-- Every selector is an edge of the concrete auxiliary graph. -/
theorem selector_mem_auxiliaryGraph (v : V) :
    P.selector v ∈ P.auxiliaryGraph.edgeSet := by
  rw [auxiliaryGraph, SimpleGraph.edgeSet_sup]
  right
  rw [SimpleGraph.edgeSet_fromEdgeSet]
  exact ⟨P.selector_mem_distinguished v, P.selector_not_isDiag v⟩

/-- Every distinguished pair is an edge of the concrete auxiliary graph. -/
theorem distinguished_mem_auxiliaryGraph_edgeSet
    {e : Sym2 (Option V)} (he : e ∈ P.distinguished) :
    e ∈ P.auxiliaryGraph.edgeSet := by
  rcases Finset.mem_image.mp he with ⟨v, _, rfl⟩
  exact P.selector_mem_auxiliaryGraph v

/-- An auxiliary edge incident with the new center belongs to the
distinguished family. -/
theorem mem_distinguished_of_mem_auxiliaryGraph_of_none_mem
    {e : Sym2 (Option V)} (he : e ∈ P.auxiliaryGraph.edgeSet)
    (hnone : (none : Option V) ∈ e) : e ∈ P.distinguished := by
  rw [auxiliaryGraph, SimpleGraph.edgeSet_sup] at he
  rcases he with hcopied | hselected
  · rw [SimpleGraph.edgeSet_map] at hcopied
    rcases hcopied with ⟨f, _, rfl⟩
    rw [Function.Embedding.sym2Map_apply] at hnone
    rcases Sym2.mem_map.mp hnone with ⟨v, _, hv⟩
    cases hv
  · rw [SimpleGraph.edgeSet_fromEdgeSet] at hselected
    exact hselected.1

/-- The new center is adjacent precisely to copied singleton vertices. -/
theorem auxiliaryGraph_adj_none_some_iff (v : V) :
    P.auxiliaryGraph.Adj none (some v) ↔ P.partner v = none := by
  constructor
  · intro hadj
    have hedge : s(none, some v) ∈ P.auxiliaryGraph.edgeSet := by
      rw [SimpleGraph.mem_edgeSet]
      exact hadj
    have hdistinguished :=
      P.mem_distinguished_of_mem_auxiliaryGraph_of_none_mem hedge
        (Sym2.mem_mk_left _ _)
    have heq : s(none, some v) = P.selector v :=
      P.eq_selector_of_mem_distinguished_of_some_mem hdistinguished
        (Sym2.mem_mk_right _ _)
    apply (P.none_mem_selector_iff v).mp
    rw [← heq]
    exact Sym2.mem_mk_left _ _
  · intro hpartner
    rw [← SimpleGraph.mem_edgeSet]
    simpa [selector, hpartner] using P.selector_mem_auxiliaryGraph v

/-- Two copied original vertices are adjacent in the auxiliary graph exactly
when they were adjacent in `G` or form one of the supplied pair classes. -/
theorem auxiliaryGraph_adj_some_some_iff (v w : V) :
    P.auxiliaryGraph.Adj (some v) (some w) ↔
      G.Adj v w ∨ P.partner v = some w := by
  rw [auxiliaryGraph, SimpleGraph.sup_adj]
  constructor
  · rintro (hcopied | hselected)
    · rcases (SimpleGraph.map_adj Function.Embedding.some G _ _).mp hcopied with
        ⟨v', w', hadj, hv', hw'⟩
      cases Option.some.inj hv'
      cases Option.some.inj hw'
      exact Or.inl hadj
    · rw [SimpleGraph.fromEdgeSet_adj] at hselected
      have heq : s(some v, some w) = P.selector v :=
        P.eq_selector_of_mem_distinguished_of_some_mem hselected.1
          (Sym2.mem_mk_left _ _)
      have hw : some w ∈ P.selector v := by
        rw [← heq]
        exact Sym2.mem_mk_right _ _
      rcases P.some_mem_selector_iff.mp hw with hwv | hpartner
      · subst w
        exact (hselected.2 rfl).elim
      · exact Or.inr hpartner
  · rintro (hadj | hpartner)
    · exact Or.inl <|
        (SimpleGraph.map_adj Function.Embedding.some G _ _).mpr
          ⟨v, w, hadj, rfl, rfl⟩
    · apply Or.inr
      rw [SimpleGraph.fromEdgeSet_adj]
      refine ⟨?_, fun hvw ↦ P.partner_ne hpartner (Option.some.inj hvw)⟩
      have heq : P.selector v = s(some v, some w) := by
        simp [selector, hpartner]
      rw [← heq]
      exact P.selector_mem_distinguished v

/-- The center degree is the number of singleton classes. -/
theorem degree_none_eq_singletonVertices_card
    [DecidableRel P.auxiliaryGraph.Adj] :
    P.auxiliaryGraph.degree none = P.singletonVertices.card := by
  have hneighbors :
      P.auxiliaryGraph.neighborFinset none =
        P.singletonVertices.map Function.Embedding.some := by
    ext v
    cases v with
    | none => simp [SimpleGraph.mem_neighborFinset]
    | some v =>
        rw [SimpleGraph.mem_neighborFinset,
          P.auxiliaryGraph_adj_none_some_iff]
        simp
  change (P.auxiliaryGraph.neighborFinset none).card =
    P.singletonVertices.card
  rw [hneighbors, Finset.card_map]

/-- Every copied original vertex gains exactly its selector neighbor. -/
theorem degree_some_eq [DecidableRel G.Adj]
    [DecidableRel P.auxiliaryGraph.Adj] (v : V) :
    P.auxiliaryGraph.degree (some v) = G.degree v + 1 := by
  cases hpartner : P.partner v with
  | none =>
      have hneighbors :
          P.auxiliaryGraph.neighborFinset (some v) =
            (G.neighborFinset v).map Function.Embedding.some ∪ {none} := by
        ext w
        cases w with
        | none =>
            rw [SimpleGraph.mem_neighborFinset,
              P.auxiliaryGraph.adj_comm,
              P.auxiliaryGraph_adj_none_some_iff]
            simp [hpartner]
        | some w =>
            rw [SimpleGraph.mem_neighborFinset,
              P.auxiliaryGraph_adj_some_some_iff]
            simp [SimpleGraph.mem_neighborFinset, hpartner]
      have hnone :
          (none : Option V) ∉
            (G.neighborFinset v).map Function.Embedding.some := by
        simp
      change (P.auxiliaryGraph.neighborFinset (some v)).card =
        (G.neighborFinset v).card + 1
      rw [hneighbors, Finset.union_singleton,
        Finset.card_insert_of_notMem hnone, Finset.card_map]
  | some w =>
      have hneighbors :
          P.auxiliaryGraph.neighborFinset (some v) =
            (G.neighborFinset v).map Function.Embedding.some ∪ {some w} := by
        ext u
        cases u with
        | none =>
            rw [SimpleGraph.mem_neighborFinset,
              P.auxiliaryGraph.adj_comm,
              P.auxiliaryGraph_adj_none_some_iff]
            simp [hpartner]
        | some u =>
            rw [SimpleGraph.mem_neighborFinset,
              P.auxiliaryGraph_adj_some_some_iff]
            simp [SimpleGraph.mem_neighborFinset, hpartner, eq_comm, or_comm]
      have hw :
          some w ∉ (G.neighborFinset v).map Function.Embedding.some := by
        simp [SimpleGraph.mem_neighborFinset,
          P.partner_nonadjacent hpartner]
      change (P.auxiliaryGraph.neighborFinset (some v)).card =
        (G.neighborFinset v).card + 1
      rw [hneighbors, Finset.union_singleton,
        Finset.card_insert_of_notMem hw, Finset.card_map]

/-- The original order plus the auxiliary center degree is twice the number
of distinguished edges. -/
theorem card_add_degree_none_eq_two_mul_distinguished_card
    [DecidableRel P.auxiliaryGraph.Adj] :
    Fintype.card V + P.auxiliaryGraph.degree none =
      2 * P.distinguished.card := by
  rw [P.degree_none_eq_singletonVertices_card,
    P.card_add_singletonVertices_card_eq_two_mul_distinguished_card]

/-- Endpoints of off-center distinguished edges are not neighbors of the new
center. -/
theorem matchingPart_avoids_center_neighbors
    {e : Sym2 (Option V)} (he : e ∈ P.matchingPart) {v : Option V}
    (hv : v ∈ e) : ¬P.auxiliaryGraph.Adj none v := by
  cases v with
  | none => exact P.auxiliaryGraph.loopless.irrefl none
  | some v =>
      intro hadj
      have hpartner : P.partner v = none :=
        (P.auxiliaryGraph_adj_none_some_iff v).mp hadj
      have heq : e = P.selector v :=
        P.eq_selector_of_mem_distinguished_of_some_mem
          (P.mem_matchingPart.mp he).1 hv
      apply P.matchingPart_off_center he
      rw [heq]
      exact (P.none_mem_selector_iff v).2 hpartner

/-- The center incidence finset is exactly the center-incident portion of the
distinguished family. -/
theorem mem_incidenceFinset_none_iff
    [DecidableRel P.auxiliaryGraph.Adj] {e : Sym2 (Option V)} :
    e ∈ P.auxiliaryGraph.incidenceFinset none ↔
      e ∈ P.distinguished ∧ (none : Option V) ∈ e := by
  rw [SimpleGraph.mem_incidenceFinset]
  change
    (e ∈ P.auxiliaryGraph.edgeSet ∧ (none : Option V) ∈ e) ↔
      e ∈ P.distinguished ∧ (none : Option V) ∈ e
  constructor
  · rintro ⟨he, hnone⟩
    exact ⟨P.mem_distinguished_of_mem_auxiliaryGraph_of_none_mem he hnone,
      hnone⟩
  · rintro ⟨he, hnone⟩
    exact ⟨P.distinguished_mem_auxiliaryGraph_edgeSet he, hnone⟩

/-- The center degree cannot exceed the number of distinguished edges. -/
theorem degree_none_le_card_distinguished
    [DecidableRel P.auxiliaryGraph.Adj] :
    P.auxiliaryGraph.degree none ≤ P.distinguished.card := by
  rw [← P.auxiliaryGraph.card_incidenceFinset_eq_degree]
  exact Finset.card_le_card fun e he ↦
    (P.mem_incidenceFinset_none_iff.mp he).1

/-- The distinguished family decomposes as the off-center matching together
with the full star at the new center. -/
theorem distinguished_decomposition
    [DecidableRel P.auxiliaryGraph.Adj] :
    P.distinguished =
      P.matchingPart ∪ P.auxiliaryGraph.incidenceFinset none := by
  ext e
  rw [Finset.mem_union, P.mem_matchingPart,
    P.mem_incidenceFinset_none_iff]
  constructor
  · intro he
    by_cases hnone : (none : Option V) ∈ e
    · exact Or.inr ⟨he, hnone⟩
    · exact Or.inl ⟨he, hnone⟩
  · rintro (⟨he, _⟩ | ⟨he, _⟩) <;> exact he

/-- Bounds on the distinguished family and on every copied degree imply the
corresponding maximum-degree bound for the auxiliary graph. -/
theorem maxDegree_le_of_bounds (D : ℕ) [DecidableRel G.Adj]
    [DecidableRel P.auxiliaryGraph.Adj]
    (hJ : P.distinguished.card ≤ D)
    (hcopy : ∀ v, G.degree v + 1 ≤ D) :
    P.auxiliaryGraph.maxDegree ≤ D := by
  apply P.auxiliaryGraph.maxDegree_le_of_forall_degree_le D
  intro v
  cases v with
  | none => exact P.degree_none_le_card_distinguished.trans hJ
  | some v =>
      rw [P.degree_some_eq]
      exact hcopy v

/-- The class count and the additive order inequality give the required
center-degree interval. -/
theorem center_degree_bounds (D : ℕ)
    [DecidableRel P.auxiliaryGraph.Adj]
    (hcard : P.distinguished.card = D)
    (horder : Fintype.card V + 2 ≤ 2 * D) :
    2 ≤ P.auxiliaryGraph.degree none ∧
      P.auxiliaryGraph.degree none ≤ D := by
  constructor
  · have horbit :=
      P.card_add_degree_none_eq_two_mul_distinguished_card
    omega
  · calc
      P.auxiliaryGraph.degree none ≤ P.distinguished.card :=
        P.degree_none_le_card_distinguished
      _ = D := hcard

/-- Once the three numerical obligations are supplied, the concrete
pair/singleton construction is a member of the structural auxiliary class. -/
theorem isAuxiliaryClassMember_of_numeric (D : ℕ)
    [DecidableRel P.auxiliaryGraph.Adj]
    (hcard : P.distinguished.card = D)
    (hmax : P.auxiliaryGraph.maxDegree ≤ D)
    (hcenter : 2 ≤ P.auxiliaryGraph.degree none ∧
      P.auxiliaryGraph.degree none ≤ D) :
    IsAuxiliaryClassMember D P.auxiliaryGraph none P.distinguished
      P.matchingPart := by
  refine
    { distinguished_edges := ?_
      matching := P.matchingPart_isEdgeMatching
      matching_off_center := ?_
      matching_avoids_center_neighbors := ?_
      decomposition := P.distinguished_decomposition
      exact_coverage := ?_
      card_distinguished := hcard
      maxDegree_bound := hmax
      center_degree := hcenter }
  · intro e he
    exact P.distinguished_mem_auxiliaryGraph_edgeSet he
  · intro e he
    exact P.matchingPart_off_center he
  · intro e he v hv
    exact P.matchingPart_avoids_center_neighbors he hv
  · intro v hv
    cases v with
    | none => exact (hv rfl).elim
    | some v => exact P.distinguished_exact_coverage v

/-- The exact class count, a copied maximum-degree bound, and the additive
order inequality discharge every numerical auxiliary-class obligation. -/
theorem isAuxiliaryClassMember_of_class_count_and_bounds (D : ℕ)
    [DecidableRel G.Adj] [DecidableRel P.auxiliaryGraph.Adj]
    (hcard : P.distinguished.card = D)
    (hG : G.maxDegree + 1 ≤ D)
    (horder : Fintype.card V + 2 ≤ 2 * D) :
    IsAuxiliaryClassMember D P.auxiliaryGraph none P.distinguished
      P.matchingPart := by
  apply P.isAuxiliaryClassMember_of_numeric D hcard
  · apply P.maxDegree_le_of_bounds D
    · exact hcard.le
    · intro v
      exact (Nat.add_le_add_right (G.degree_le_maxDegree v) 1).trans hG
  · exact P.center_degree_bounds D hcard horder

/-- In the half-order regime, an exact class count of `maxDegree + 1`
specializes the preceding numerical wrapper without any parity assumption. -/
theorem isAuxiliaryClassMember_of_highDegree [DecidableRel G.Adj]
    [DecidableRel P.auxiliaryGraph.Adj]
    (hclasses : P.distinguished.card = G.maxDegree + 1)
    (hdense : Fintype.card V ≤ 2 * G.maxDegree) :
    IsAuxiliaryClassMember (G.maxDegree + 1) P.auxiliaryGraph none
      P.distinguished P.matchingPart := by
  apply P.isAuxiliaryClassMember_of_class_count_and_bounds
    (G.maxDegree + 1) hclasses le_rfl
  omega

/-- The selected auxiliary edge as an element of the auxiliary edge subtype. -/
def classEdge (v : V) : P.auxiliaryGraph.edgeSet :=
  ⟨P.selector v, P.selector_mem_auxiliaryGraph v⟩

/-- The canonical copy of `G` inside the concrete auxiliary graph. -/
def originalCopy : SimpleGraph.Copy G P.auxiliaryGraph :=
  (SimpleGraph.Copy.ofLE _ _ le_sup_left).comp
    (SimpleGraph.Embedding.map Function.Embedding.some G).toCopy

@[simp]
theorem originalCopy_apply (v : V) : P.originalCopy v = some v := by
  rfl

/-- The copied auxiliary edge corresponding to an original edge. -/
def originalEdge (e : G.edgeSet) : P.auxiliaryGraph.edgeSet :=
  P.originalCopy.toLineGraphEmbedding e

@[simp]
theorem originalEdge_val (e : G.edgeSet) :
    (P.originalEdge e : Sym2 (Option V)) =
      (e : Sym2 V).map Option.some := by
  change Sym2.map P.originalCopy (e : Sym2 V) =
    Sym2.map Option.some (e : Sym2 V)
  apply Sym2.map_congr
  intro v _
  exact P.originalCopy_apply v

omit [Fintype V] [DecidableEq V] in
/-- A selector edge cannot coincide with a copied original edge incident with
the vertex which chose it. -/
theorem selector_ne_mapped_original_of_incident
    {v : V} {e : G.edgeSet} (hve : Incident v e) :
    P.selector v ≠ (e : Sym2 V).map Option.some := by
  intro heq
  cases hpartner : P.partner v with
  | none =>
      have hnone : (none : Option V) ∈ (e : Sym2 V).map Option.some := by
        rw [← heq]
        simp [selector, hpartner]
      simp at hnone
  | some w =>
      have hsome : some w ∈ (e : Sym2 V).map Option.some := by
        rw [← heq]
        simp [selector, hpartner]
      rcases Sym2.mem_map.mp hsome with ⟨w', hw'e, hsomeEq⟩
      have hw' : w' = w := Option.some.inj hsomeEq
      subst w'
      have hedge : (e : Sym2 V) = s(v, w) :=
        (Sym2.mem_and_mem_iff (P.partner_ne hpartner)).mp ⟨hve, hw'e⟩
      apply P.partner_nonadjacent hpartner
      rw [← SimpleGraph.mem_edgeSet, ← hedge]
      exact e.2

/-- The concrete pair/singleton construction preserves the three conflict
relations required by the abstract decoding interface. -/
def extension : Extension G P.auxiliaryGraph where
  classEdge := P.classEdge
  originalEdge := P.originalEdge
  classEdge_ne_of_adj := fun hadj ↦ by
    intro heq
    apply P.selector_ne_of_adj hadj
    exact congrArg Subtype.val heq
  originalEdge_adj := fun hadj ↦ by
    exact P.originalCopy.toLineGraphEmbedding.toHom.map_adj hadj
  classEdge_adj_original := fun {v e} hve ↦ by
    rw [SimpleGraph.lineGraph_adj_iff_exists]
    refine ⟨?_, some v, ?_, ?_⟩
    · intro heq
      apply P.selector_ne_mapped_original_of_incident hve
      have hval := congrArg Subtype.val heq
      simpa only [classEdge, originalEdge_val] using hval
    · exact P.some_mem_selector v
    · rw [originalEdge_val]
      exact Sym2.mem_map.mpr ⟨v, hve, rfl⟩

/-- Every selector used by the concrete extension lies in the distinguished
edge set expected by the abstract transfer theorem. -/
theorem classEdge_mem_distinguishedEdgeSet (v : V) :
    P.extension.classEdge v ∈
      distinguishedEdgeSet P.auxiliaryGraph P.distinguished := by
  change P.selector v ∈ P.distinguished
  exact P.selector_mem_distinguished v

end Finite

end PairSingletonWitness

end TotalColoring.Auxiliary
