import TotalColoring

#check TotalColoring.InAuxiliaryClass
#check TotalColoring.ExtensionPalette
#check TotalColoring.HasValidRainbowColoring
#check TotalColoring.MinimalExtraction.hasValidRainbowColoring_of_inAuxiliaryClass
#check TotalColoring.Auxiliary.Extension.decode_valid
#check TotalColoring.Auxiliary.Extension.exists_valid_decode_of_inAuxiliaryClass
#check TotalColoring.Auxiliary.PairSingletonWitness
#check TotalColoring.Auxiliary.PairSingletonWitness.auxiliaryGraph
#check TotalColoring.Auxiliary.PairSingletonWitness.extension
#check TotalColoring.Auxiliary.PairSingletonWitness.classEdge_mem_distinguishedEdgeSet
#check TotalColoring.Auxiliary.PairSingletonWitness.degree_some_eq
#check TotalColoring.Auxiliary.PairSingletonWitness.card_add_degree_none_eq_two_mul_distinguished_card
#check TotalColoring.Auxiliary.PairSingletonWitness.isAuxiliaryClassMember_of_class_count_and_bounds
#check TotalColoring.Auxiliary.PairSingletonWitness.isAuxiliaryClassMember_of_highDegree
#check TotalColoring.Auxiliary.EquitableIndependentPartition
#check TotalColoring.Auxiliary.EquitableIndependentPartition.toPairSingletonWitness
#check TotalColoring.Auxiliary.EquitableIndependentPartition.distinguished_card
#check TotalColoring.Auxiliary.EquitableIndependentPartition.highDegreeWitness_inAuxiliaryClass
#check TotalColoring.Auxiliary.EquitableIndependentPartition.exists_valid_assignment_of_highDegreePartition
#check TotalColoring.MatchingLowerBound.exists_matchingGraph_edgeFinset_card_ge
#check TotalColoring.MatchingLowerBound.exists_complement_matchingGraph_edgeFinset_card_ge
#check TotalColoring.MatchingLowerBound.exists_complement_matchingGraph_edgeFinset_card_eq
#check TotalColoring.Auxiliary.exists_pairSingletonWitness_of_highDegree
#check TotalColoring.Auxiliary.exists_valid_assignment_of_highDegree_nonempty
#check TotalColoring.exists_valid_assignment_of_isEmpty
#check TotalColoring.exists_valid_assignment_of_highDegree

-- Proof branch `agent/independent-seed-endpoint`, source commit
-- `cc4dd7ae1d858ea0583549f88707952e2414bf60`, tree
-- `9af6a84e1305aed9a0156dcd59c279de792dea4a`; not yet on `main`.
#check TotalColoring.exists_valid_assignment_of_independentSeedPeel
#check TotalColoring.exists_valid_assignment_of_maxDegreeIndependentSeedPeel
#check TotalColoring.Certificate.checkExtension_sound
